export const ugDegrees = [
  "5 year BS-MS Dual Degree Programme",
  "5 year Integrated M.Sc",
  "5 year dual degree B.E. and M.E.",
  "5 year dual degree B.Tech and M.Tech",
  "A level",
  "A.I.S.",
  "ALCCS",
  "AMIE",
  "AMIETE",
  "B-Pharma",
  "B.A.M.S",
  "B.ARCH",
  "B.Com",
  "B.D.S.",
  "B.E.",
  "B.EL.ED",
  "B.Ed",
  "B.Sc",
  "B.Tech",
  "BA",
  "BCA",
  "CA",
  "IETE",
  "Integrated M.Sc-Ph.D",
  "Integrated MA",
  "Integrated MBA",
  "Integrated MCA with BCA",
  "LLB",
  "OTHER"
];