export const ugDisciplines = [
  "Account and finance",
  "Accountancy",
  "Actuarial Science",
  "Advanced Biochemistry",
  "Advanced Manufacturing",
  "Advanced Zoology and Biotechnology",
  "Advertising Management and Public Relations",
  "Aerodynamics",
  "Aeronautical Engineering",
  "Aeronautical Science",
  "Aeronautical",
  "Aerospace Engineering",
  "Aerospace Propulsion",
  "Aerospace",
  "Agricultural Biotechnology",
  "Agricultural Botany",
  "Agricultural Economics and Business Management",
  "Agricultural Economics",
  "Agricultural Engineering",
  "Agricultural Extension Education",
  "Agricultural Microbiology",
  "Agricultural Physics",
  "Agricultural Statistics",
  "Agricultural",
  "Agriculture Chemistry and Soil Science",
  "Agriculture and Food Engineering",
  "Agriculture",
  "Agro-meteorology",
  "Agroforestry",
  "Agronomy",
  "Air Armament",
  "Airlines Tourism and Hospitality Management",
  "Alloy Technology",
  "Anaesthesia Technology",
  "Analytical Chemistry",
  "Anatomy",
  "Animal Biotechnology",
  "Animal Nutrition",
  "Animal Science",
  "Animation Filmmaking",
  "Animation and Visual Effects",
  "Animation",
  "Anthropology",
  "Apparel Technology and Management",
  "Apparel and Textiles",
  "Applications of Mathematics",
  "Applied Biology",
  "Applied Biotechnology",
  "Applied Chemistry",
  "Applied Econometrics and Business Forecasting",
  "Applied Economics",
  "Applied Electronics and Instrumentation",
  "Applied Electronics",
  "Applied Fisheries and Aquaculture",
  "Applied Genetics",
  "Applied Geography",
  "Applied Geology",
  "Applied Geophysics",
  "Applied Mathematics and Computing",
  "Applied Mathematics",
  "Applied Mechanics",
  "Applied Microbiology",
  "Applied Nutrition",
  "Applied Optics",
  "Applied Physics",
  "Applied Plant Science",
  "Applied Psychology",
  "Applied Science",
  "Applied Statistics and Informatics",
  "Applied Zoology",
  "Aquaculture",
  "Architecture",
  "Artificial Intelligence",
  "Artificial Intelligence and Machine Learning",
  "Astronomy",
  "Astrophysics",
  "Automobile Engineering",
  "Aviation",
  "Avionics",
  "Banking and Finance",
  "Big Data Analytics",
  "Bioinformatics",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Science",
  "Biophysics",
  "Biostatistics",
  "Biotechnology",
  "Botany",
  "Business Administration",
  "CAD CAM",
  "Cardiovascular Technology",
  "Cell and Molecular Biology",
  "Ceramic Engineering",
  "Chemical Engineering",
  "Chemical Sciences",
  "Chemistry",
  "Civil Engineering",
  "Clinical Microbiology",
  "Clinical Psychology",
  "Cloud Computing",
  "Cognitive Science",
  "Commerce",
  "Communication",
  "Computer Applications",
  "Computer Engineering",
  "Computer Science",
  "Computer Science and Engineering",
  "Computer Science and Technology",
  "Computer Technology",
  "Construction Engineering",
  "Control Systems",
  "Cyber Security",
  "Data Analytics",
  "Data Mining and Warehousing",
  "Data Science",
  "Design",
  "Digital Communication",
  "Digital Electronics",
  "Disaster Management",
  "Earth Science",
  "Ecology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electrical and Electronics Engineering",
  "Electronics",
  "Electronics Engineering",
  "Electronics and Communication",
  "Electronics and Communication Engineering",
  "Embedded Systems",
  "Energy Systems",
  "Engineering Physics",
  "English",
  "Environmental Engineering",
  "Environmental Science",
  "Environmental Studies",
  "Fashion Design",
  "Finance",
  "Food Science",
  "Food Technology",
  "Forensic Science",
  "Forestry",
  "Game Design and Development",
  "Genetics",
  "Geography",
  "Geology",
  "Geophysics",
  "Graphics and Multimedia",
  "Hardware and Networking",
  "Health Science",
  "History",
  "Home Science",
  "Hospitality Management",
  "Hotel Management",
  "Human Genetics",
  "Information Science",
  "Information Technology",
  "Instrumentation Engineering",
  "Interior Design",
  "Journalism",
  "Journalism and Mass Communication",
  "Law",
  "Life Sciences",
  "Management",
  "Manufacturing Engineering",
  "Marine Engineering",
  "Marketing",
  "Mass Communication",
  "Material Science",
  "Mathematics",
  "Mathematics and Computing",
  "Mechanical Engineering",
  "Mechatronics",
  "Media Technology",
  "Medical Biotechnology",
  "Medical Lab Technology",
  "Medical Physics",
  "Medical Technology",
  "Metallurgical Engineering",
  "Meteorology",
  "Microbiology",
  "Mining Engineering",
  "Molecular Biology",
  "Multimedia",
  "Nanotechnology",
  "Naval Architecture",
  "Network Security",
  "Neuroscience",
  "Nuclear Engineering",
  "Nuclear Physics",
  "Nursing",
  "Nutrition",
  "Ocean Engineering",
  "Oceanography",
  "Operations Research",
  "Optometry",
  "Organic Chemistry",
  "Petroleum Engineering",
  "Pharmaceutical Chemistry",
  "Pharmacy",
  "Photography",
  "Physics",
  "Physiology",
  "Physiotherapy",
  "Plant Science",
  "Political Science",
  "Polymer Technology",
  "Power Engineering",
  "Production Engineering",
  "Psychology",
  "Public Health",
  "Radiology",
  "Remote Sensing and GIS",
  "Renewable Energy",
  "Robotics",
  "Rural Development",
  "Seed Science",
  "Signal Processing",
  "Software Engineering",
  "Soil Science",
  "Sports Science",
  "Statistics",
  "Structural Engineering",
  "Sustainable Development",
  "Telecommunication Engineering",
  "Textile Engineering",
  "Thermal Engineering",
  "Tourism",
  "Transportation Engineering",
  "VFX",
  "VLSI Design",
  "Veterinary Science",
  "Virology",
  "Visual Communication",
  "Water Resources",
  "Wildlife Science",
  "Wireless Communication",
  "Yoga",
  "Zoology",
  "OTHER"
];